name: expense_api
description: The interface and models for the expense API.
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  errors:
    path: ../errors
  fpdart: ^1.1.0
  equatable: ^2.0.5
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0