// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YMYZPHrA8WSY0HqB8LGRJPm8llUCW-g',
    appId: '1:332343858798:web:da2c215a1ed7abab77b87f',
    messagingSenderId: '332343858798',
    projectId: 'wallet-assesment',
    authDomain: 'wallet-assesment.firebaseapp.com',
    storageBucket: 'wallet-assesment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXHNuWpqC_4H1xKiJBm8e0DKhLV_rG_uI',
    appId: '1:332343858798:android:a0ef683b5d22765c77b87f',
    messagingSenderId: '332343858798',
    projectId: 'wallet-assesment',
    storageBucket: 'wallet-assesment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6QZX5JTa2fR0WPMMYYRRo3-_KbyXfAQM',
    appId: '1:332343858798:ios:179e2988a236bda677b87f',
    messagingSenderId: '332343858798',
    projectId: 'wallet-assesment',
    storageBucket: 'wallet-assesment.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6QZX5JTa2fR0WPMMYYRRo3-_KbyXfAQM',
    appId: '1:332343858798:ios:179e2988a236bda677b87f',
    messagingSenderId: '332343858798',
    projectId: 'wallet-assesment',
    storageBucket: 'wallet-assesment.appspot.com',
    iosBundleId: 'com.example.expenseTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1YMYZPHrA8WSY0HqB8LGRJPm8llUCW-g',
    appId: '1:332343858798:web:4d372d4cceef831677b87f',
    messagingSenderId: '332343858798',
    projectId: 'wallet-assesment',
    authDomain: 'wallet-assesment.firebaseapp.com',
    storageBucket: 'wallet-assesment.appspot.com',
  );
}
