name: expense_api_client
description: A client for the expense API

publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  errors:
    path: ../errors
  equatable: ^2.0.5
  fpdart: ^1.1.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  secure_storage_repository:
    path: ../secure_storage_repository

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
