name: expense_api_repository
description: A package for interacting with the expense API.
publish_to: none

version: 0.0.1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dart_jsonwebtoken: ^2.14.0
  expense_api_client:
    path: ../expense_api_client
  expense_api:
    path: ../expense_api
  fpdart: ^1.1.0
  equatable: ^2.0.5
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test:
